# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\"\xd5\x01\n\x07\x43ommand\x12\x14\n\x07minTemp\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x14\n\x07maxTemp\x18\x02 \x01(\x02H\x01\x88\x01\x01\x12\x13\n\x06minHum\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06maxHum\x18\x04 \x01(\x02H\x03\x88\x01\x01\x12\x15\n\x08minMoist\x18\x05 \x01(\x02H\x04\x88\x01\x01\x12\x15\n\x08maxMoist\x18\x06 \x01(\x02H\x05\x88\x01\x01\x42\n\n\x08_minTempB\n\n\x08_maxTempB\t\n\x07_minHumB\t\n\x07_maxHumB\x0b\n\t_minMoistB\x0b\n\t_maxMoistb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMMAND']._serialized_start=18
  _globals['_COMMAND']._serialized_end=231
# @@protoc_insertion_point(module_scope)
