# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\"o\n\x07\x43ommand\x12\x0f\n\x07minTemp\x18\x01 \x01(\x02\x12\x0f\n\x07maxTemp\x18\x02 \x01(\x02\x12\x0e\n\x06minHum\x18\x03 \x01(\x02\x12\x0e\n\x06maxHum\x18\x04 \x01(\x02\x12\x10\n\x08minMoist\x18\x05 \x01(\x02\x12\x10\n\x08maxMoist\x18\x06 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_COMMAND']._serialized_start=17
  _globals['_COMMAND']._serialized_end=128
# @@protoc_insertion_point(module_scope)
