name: plantwatch_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  dotenv: ^4.1.0
  logging: ^1.1.1
  mongo_dart: ^0.9.1
dependency_overrides:
  basic_utils: "5.3.0"